sudo: required
services:
  - docker

before_install:
  - docker build -t parijat/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true parijat/react-test npm test

after_success: 
  - docker build -t parijat69/multi-client ./client 
  - docker build -t parijat69/multi-nginx ./nginx
  - docker build -t parijat69/multi-server ./server
  - docker build -t parijat69/multi-worker ./worker
  # push the images to the docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push parijat69/multi-client
  - docker push parijat69/multi-nginx
  - docker push parijat69/multi-server
  - docker push parijat69/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: multiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-978328486607
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY