sudo: required
services: 
  - docker

before_install:
  - docker build -t parijat/docker-react -f dockerfile.dev .

script:
  - docker run parijat/docker-react npm run build -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-978328486607"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY